version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    container_name: postgres
    image: postgres:9.6
    environment:
      - "POSTGRES_DB=emp"
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=root"
    ports:
      - "54325:5432"
